name: Build Debian Package (bootmac)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo (INI WAJIB)
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git build-essential udev systemd devscripts debhelper meson ninja-build pkg-config tree

      - name: Clone and build bootmac source
        run: |
          git clone https://gitlab.postmarketos.org/postmarketOS/bootmac.git bootmac_source
          cd bootmac_source
          git submodule update --init --recursive
          meson setup output .
          meson compile -C output
          DESTDIR="tmp" meson install --no-rebuild -C output
          cp -r output/* ../bootmac
          cd ..
          dpkg-deb --build --root-owner-group bootmac

      - name: Show build result
        run: |
          ls -lh bootmac/..
          tree bootmac/..

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: bootmac
          path: "*.deb"

      - name: "GitHub Release"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: bootmac
          name: "bootmac from PMOS"
          draft: false
          prerelease: false
          files: "*.deb"
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}