name: Build Debian Package (msm-modem)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo (INI WAJIB)
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git build-essential devscripts debhelper meson ninja-build pkg-config tree

      - name: Clone and build msm-modem source
        run: |
          git clone https://gitlab.postmarketos.org/postmarketOS/msm-modem.git modem_source
          cd modem_source
          git submodule update --init --recursive
          meson -Dwwan-port=true -Ddownstream=true output .
          meson compile -C output
          DESTDIR="tmp" meson install --no-rebuild -C output
          cp -r output/tmp/* ../msm-modem
          cd ..
          dpkg-deb --build --root-owner-group msm-modem

      - name: Show build result
        run: |
          ls -lh msm-modem/..
          tree msm-modem/..

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: msm-modem
          path: "*.deb"

      - name: "GitHub Release"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: msm-modem
          name: "MSM Modem from PMOS"
          draft: false
          prerelease: false
          files: "*.deb"
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}