name: Build pd-mapper Debian Package

on:
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev fakeroot

      - name: Build .deb package
        run: |
          chmod 755 pd-mapper/DEBIAN/postinst
          chmod 755 pd-mapper/DEBIAN/postrm
          fakeroot dpkg-deb --build pd-mapper pd-mapper.deb

      - name: Show output
        run: |
          ls -lah *.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pd-mapper-deb
          path: pd-mapper.deb

      - name: "GitHub Release"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: pd-mapper
          name: "pd-mapper from PMOS"
          draft: false
          prerelease: false
          files: "*.deb"
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}